from typing import List, Dict, Any

def generate_markdown_export(ip_records: List[Dict[str, Any]], subnet: str = "192.168.2.0/24") -> str:
    active_records = [r for r in ip_records if r.get("status") in ["Active", "Reserved"]]
    free_records = [r for r in ip_records if r.get("status") == "Free"]
    
    total_services = sum(len(r.get("services", [])) for r in active_records)
    
    md = []
    md.append(f"# Homelab IPAM Inventory - {subnet}\n")
    md.append(f"**Total IPs Tracked:** {len(ip_records)} | **Active/Reserved:** {len(active_records)} | **Free:** {len(free_records)} | **Discovered Services:** {total_services}\n")
    md.append("---\n")
    
    # Group active records by Type Tag
    grouped = {}
    for r in active_records:
        tag = r.get("type_tag", "Other / General")
        if tag not in grouped:
            grouped[tag] = []
        grouped[tag].append(r)
        
    for tag, records in grouped.items():
        md.append(f"## {tag}\n")
        md.append("| IP Address | Hostname | Status | Services & Exposed Ports | MAC Address | Notes |")
        md.append("|:-----------|:---------|:-------|:--------------------------|:------------|:------|")
        
        for r in records:
            ip = r.get("ip", "")
            host = r.get("hostname", "-") or "-"
            status = r.get("status", "Active")
            mac = r.get("mac_address", "-") or "-"
            notes = r.get("notes", "-") or "-"
            
            services = r.get("services", [])
            if services:
                service_strs = []
                for s in services:
                    port = s.get("port", "")
                    name = s.get("name", "Service")
                    url = s.get("url", "")
                    if url:
                        service_strs.append(f"[{name} ({port})]({url})")
                    else:
                        service_strs.append(f"{name} ({port})")
                svc_fmt = ", ".join(service_strs)
            else:
                svc_fmt = "*None*"
                
            md.append(f"| `{ip}` | `{host}` | **{status}** | {svc_fmt} | `{mac}` | {notes} |")
        md.append("\n")
        
    # Section for Free / Available IP ranges
    if free_records:
        md.append("## Available / Free IPs\n")
        free_ips = [r["ip"] for r in free_records]
        md.append(f"**Total Available:** {len(free_ips)} IPs\n")
        # Format as compact code blocks or comma list
        ip_chips = ", ".join([f"`{ip}`" for ip in free_ips[:30]])
        if len(free_ips) > 30:
            ip_chips += f" ...and {len(free_ips) - 30} more."
        md.append(ip_chips + "\n")
        
    md.append("\n*Generated by Homelab IPAM Auto-Discovery Engine*\n")
    return "\n".join(md)


def generate_text_export(ip_records: List[Dict[str, Any]], subnet: str = "192.168.2.0/24") -> str:
    active_records = [r for r in ip_records if r.get("status") in ["Active", "Reserved"]]
    free_records = [r for r in ip_records if r.get("status") == "Free"]
    
    txt = []
    txt.append("=========================================================================")
    txt.append(f"                      HOMELAB IPAM NETWORK REPORT                        ")
    txt.append(f" Subnet: {subnet}                                                       ")
    txt.append(f" Active: {len(active_records):<3} | Reserved: {sum(1 for r in ip_records if r.get('status')=='Reserved'):<3} | Free: {len(free_records):<3} | Total: {len(ip_records)}")
    txt.append("=========================================================================\n")
    
    header = f"{'IP ADDRESS':<16} {'STATUS':<9} {'TYPE TAG':<22} {'HOSTNAME':<22} {'SERVICES / PORTS':<35}"
    txt.append(header)
    txt.append("-" * len(header))
    
    for r in ip_records:
        if r.get("status") == "Free" and not r.get("hostname"):
            continue # Skip blank free IPs in text list to keep concise, or show summary
            
        ip = r.get("ip", "")
        status = r.get("status", "Active")
        type_tag = r.get("type_tag", "Unassigned")[:20]
        host = (r.get("hostname", "") or "-")[:20]
        
        services = r.get("services", [])
        if services:
            svc_parts = [f"{s.get('name', 'App')}:{s.get('port', '')}" for s in services]
            svc_str = ", ".join(svc_parts)[:33]
        else:
            svc_str = "-"
            
        txt.append(f"{ip:<16} {status:<9} {type_tag:<22} {host:<22} {svc_str:<35}")
        
    txt.append("\n" + "=" * 73)
    txt.append(f" Summary: {len(free_records)} unassigned IPs remaining in range {subnet}")
    txt.append("=========================================================================\n")
    return "\n".join(txt)
