import express from 'express';
import path from 'path';
import fs from 'fs';
import { createServer as createViteServer } from 'vite';
import { store, IPRecord } from './server/ipam-store';
import { runSubnetScan, getScanProgress } from './server/network-scanner';

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json({ limit: '10mb' }));

  // API Endpoints
  app.get('/api/ips', (req, res) => {
    res.json(store.getAll());
  });

  app.get('/api/stats', (req, res) => {
    res.json(store.getStats());
  });

  app.put('/api/ips/:ip', (req, res) => {
    try {
      const updated = store.update(req.params.ip, req.body);
      res.json(updated);
    } catch (err: any) {
      res.status(400).json({ error: err.message });
    }
  });

  app.post('/api/scan', async (req, res) => {
    // Trigger async scan in background
    runSubnetScan().catch((err) => console.error('Scan error:', err));
    res.json({ message: 'Scan started', status: getScanProgress() });
  });

  app.get('/api/scan/progress', (req, res) => {
    res.json(getScanProgress());
  });

  // Alias routes for exports
  app.get('/export/md', (req, res) => res.redirect('/api/export/md'));
  app.get('/export/txt', (req, res) => res.redirect('/api/export/txt'));

  // Markdown Export endpoint
  app.get('/api/export/md', (req, res) => {
    const records = store.getAll();
    const active = records.filter((r) => r.status !== 'Free');
    const free = records.filter((r) => r.status === 'Free');

    let md = `# Homelab IPAM Inventory - 192.168.2.0/24\n\n`;
    md += `**Total IPs Tracked:** ${records.length} | **Active/Reserved:** ${active.length} | **Free:** ${free.length}\n\n`;
    md += `---\n\n`;

    // Group active by typeTag
    const grouped: Record<string, IPRecord[]> = {};
    active.forEach((r) => {
      const tag = r.typeTag || 'Other';
      if (!grouped[tag]) grouped[tag] = [];
      grouped[tag].push(r);
    });

    for (const [tag, recs] of Object.entries(grouped)) {
      md += `## ${tag}\n\n`;
      md += `| IP Address | Hostname | Status | Services & Ports | MAC Address | Notes |\n`;
      md += `|:-----------|:---------|:-------|:-----------------|:------------|:------|\n`;

      recs.forEach((r) => {
        const svcs = r.services.map((s) => `[${s.name} (:${s.port})](${s.url || '#'})`).join(', ') || '*None*';
        md += `| \`${r.ip}\` | \`${r.hostname || '-'}\` | **${r.status}** | ${svcs} | \`${r.macAddress || '-'}\` | ${r.notes || '-'} |\n`;
      });
      md += `\n`;
    }

    if (free.length > 0) {
      md += `## Available Free IP Range\n\n`;
      md += `**Total Free:** ${free.length} IPs\n\n`;
      md += free.map((f) => `\`${f.ip}\``).join(', ') + `\n\n`;
    }

    md += `*Generated by Homelab IPAM Manager*\n`;

    res.setHeader('Content-Type', 'text/markdown');
    res.setHeader('Content-Disposition', 'attachment; filename="homelab-ipam-192.168.2.0.md"');
    res.send(md);
  });

  // Plain Text Export endpoint
  app.get('/api/export/txt', (req, res) => {
    const records = store.getAll();
    const active = records.filter((r) => r.status !== 'Free');

    let txt = `=========================================================================\n`;
    txt += `                      HOMELAB IPAM NETWORK REPORT                        \n`;
    txt += ` Subnet: 192.168.2.0/24                                                   \n`;
    txt += ` Active: ${active.length} | Total: ${records.length}\n`;
    txt += `=========================================================================\n\n`;

    const header = `${'IP ADDRESS'.padEnd(16)} ${'STATUS'.padEnd(9)} ${'TYPE TAG'.padEnd(22)} ${'HOSTNAME'.padEnd(22)} ${'SERVICES / PORTS'}`;
    txt += header + `\n` + '-'.repeat(80) + `\n`;

    records.forEach((r) => {
      if (r.status === 'Free' && !r.hostname) return;
      const ip = r.ip.padEnd(16);
      const status = r.status.padEnd(9);
      const tag = (r.typeTag || 'Unassigned').slice(0, 20).padEnd(22);
      const host = (r.hostname || '-').slice(0, 20).padEnd(22);
      const svcs = r.services.map((s) => `${s.name}:${s.port}`).join(', ') || '-';
      txt += `${ip} ${status} ${tag} ${host} ${svcs}\n`;
    });

    txt += `\n=========================================================================\n`;

    res.setHeader('Content-Type', 'text/plain');
    res.setHeader('Content-Disposition', 'attachment; filename="homelab-ipam-192.168.2.0.txt"');
    res.send(txt);
  });

  // JSON Export
  app.get('/api/export/json', (req, res) => {
    res.setHeader('Content-Disposition', 'attachment; filename="homelab-ipam-backup.json"');
    res.json(store.getAll());
  });

  // Docker Codebase Files Endpoint
  app.get('/api/docker-files', (req, res) => {
    const files = [
      { name: 'main.py', path: '/main.py' },
      { name: 'scanner.py', path: '/scanner.py' },
      { name: 'exporter.py', path: '/exporter.py' },
      { name: 'templates/index.html', path: '/templates/index.html' },
      { name: 'Dockerfile', path: '/Dockerfile' },
      { name: 'docker-compose.yml', path: '/docker-compose.yml' }
    ];

    const result = files.map((f) => {
      const fullPath = path.join(process.cwd(), f.path);
      let content = '';
      if (fs.existsSync(fullPath)) {
        content = fs.readFileSync(fullPath, 'utf-8');
      }
      return { name: f.name, content };
    });

    res.json(result);
  });

  // Vite middleware for dev / static serving for prod
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa'
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server listening on http://0.0.0.0:${PORT}`);
  });
}

startServer();
